version: '2'
services:
  node:
    build: 
      context: .
      dockerfile: docker/node.dockerfile
    ports:
     - "3001:3001"
  nginx:
    build: 
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
     - "3000:80"